# Generated by Django 3.2.12 on 2022-03-19 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(verbose_name='date logged')),
                ('ticket_quantity', models.IntegerField(default=0)),
                ('is_club_booking', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('age_rating', models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12A', '12A'), ('12', '12'), ('15', '15'), ('18', '18')], max_length=3)),
                ('duration', models.DurationField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.IntegerField()),
                ('is_full', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('showing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('showing_datetime', models.DateTimeField(verbose_name='date logged')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.film')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('purchased_datetime', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('street_address', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ticket_price', models.FloatField()),
                ('ticket_type', models.CharField(max_length=10)),
                ('showing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.showing')),
            ],
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.account')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('seat_type', models.CharField(max_length=50)),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.screen')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.venue'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('landline', models.IntegerField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.account')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_social_distancing', models.BooleanField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.account')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uweflix.club'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uweflix.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.ticket'),
        ),
        migrations.CreateModel(
            name='AccountAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_discount', models.BooleanField(verbose_name=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.account')),
            ],
        ),
    ]
