# Generated by Django 3.2.12 on 2022-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_time',
            field=models.CharField(max_length=25),
        ),
    ]
