# Generated by Django 3.1.2 on 2022-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_club',
            field=models.BooleanField(default=True),
        ),
    ]
