# Generated by Django 3.2.12 on 2022-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
