# Generated by Django 3.1.2 on 2022-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0002_auto_20220321_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='landline',
            field=models.IntegerField(null=True),
        ),
    ]
