# Generated by Django 3.1.2 on 2022-04-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0002_auto_20220324_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='club',
            name='token',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.customer'),
        ),
    ]
