# Generated by Django 3.1.2 on 2022-04-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0002_auto_20220324_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_date',
        ),
    ]
