# Generated by Django 3.1.2 on 2022-03-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_auto_20220324_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflix.customer'),
        ),
        migrations.AlterField(
            model_name='club',
            name='landline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
