# Generated by Django 3.1.2 on 2022-03-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
