# Generated by Django 3.1.2 on 2022-04-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_auto_20220417_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='customer_id',
        ),
    ]
