# Generated by Django 3.1.2 on 2022-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_auto_20220405_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
