# Generated by Django 3.1.2 on 2022-04-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0004_account_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='tokenID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflix.token'),
        ),
    ]
