# Generated by Django 3.1.2 on 2022-04-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0006_customer_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tokenID',
            new_name='token_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='surname',
        ),
    ]
