# Generated by Django 3.1.2 on 2022-04-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0007_auto_20220406_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='token_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflix.token'),
        ),
    ]
